In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv("../datasets/student_multiple_features.csv")
df.head(5) # display first five rows
df.tail(5) # display five last rows 
df.shape # display the shape of the dataset
df.info() # display information of dataset
df.describe() # display statistical summary
df

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student        20 non-null     str
 1   StudyHours     20 non-null     int64
 2   Attendance     20 non-null     str
 3   PreviousMarks  19 non-null     float64
 4   FinalMarks     20 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 932.0 bytes

   Student  StudyHours Attendance  PreviousMarks  FinalMarks
0    Aarav           2         70           38.0          42
1     Sita           3         75           45.0          50
2      Ram           4         80           52.0          58
3   Anisha           5         85           60.0          68
4    Rohan           6         90           68.0          78
5    Priya           7         92           75.0          85
6    Kiran           8         95           82.0          92
7    Nabin           4         78           55.0          60
8    Suman           5         82           63.0          70
9   Alisha           6         88           70.0          79
10  Bikash           7         91           78.0          87
11  Sabina           8         96           85.0          95
12  Roshan           3         72           48.0          52
13    Puja           9         98           90.0          98
14  Manish           5         86           66.0          73
15  Aakash           6     Absent           72.0          81
16    Rita           4         79           58.0          61
17   Deepa           7         90            NaN          89
18  Sanjay           8         97           88.0          96
19  Kushal           5         84           64.0          74

In [19]:
# Handling Missing values
df.isnull().sum()
df["PreviousMarks"] = df["PreviousMarks"].fillna(df["PreviousMarks"].mean())
df["Attendance"] = pd.to_numeric(df["Attendance"], errors = "coerce")
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].mean())
df

   Student  StudyHours  Attendance  PreviousMarks  FinalMarks
0    Aarav           2   70.000000      38.000000          42
1     Sita           3   75.000000      45.000000          50
2      Ram           4   80.000000      52.000000          58
3   Anisha           5   85.000000      60.000000          68
4    Rohan           6   90.000000      68.000000          78
5    Priya           7   92.000000      75.000000          85
6    Kiran           8   95.000000      82.000000          92
7    Nabin           4   78.000000      55.000000          60
8    Suman           5   82.000000      63.000000          70
9   Alisha           6   88.000000      70.000000          79
10  Bikash           7   91.000000      78.000000          87
11  Sabina           8   96.000000      85.000000          95
12  Roshan           3   72.000000      48.000000          52
13    Puja           9   98.000000      90.000000          98
14  Manish           5   86.000000      66.000000          73
15  Aakash           6   85.684211      72.000000          81
16    Rita           4   79.000000      58.000000          61
17   Deepa           7   90.000000      66.157895          89
18  Sanjay           8   97.000000      88.000000          96
19  Kushal           5   84.000000      64.000000          74

In [36]:
features = ["StudyHours", "Attendance", "PreviousMarks"]
target = "FinalMarks"

X = df[features].to_numpy()
y = df[target].to_numpy()

# Split to 80% and 20%
split = int( len(df) * 0.8)

# Training data
X_train = X[:split]
y_train = y[:split]

# Create Model
model = LinearRegression()
model.fit(X_train, y_train)

# Calculate
print("Bias:", model.intercept_)
print("Coefficient of StudyHours", model.coef_[0])
print("Coefficient of Attendance", model.coef_[1])
print("Coefficient of PreviousMarks", model.coef_[2])

# Prediction
features = [[5, 10, 70],
           [7, 95, 82],
           [3, 75, 55]
           ]

predictions = model.predict(features)

print("Final Marks of Student A", predictions[0])
print("Final Marks of Student B", predictions[1])
print("Final Marks of Student C", predictions[2])

Bias: -24.854065141911377
Coefficient of StudyHours -1.0577057607486544
Coefficient of Attendance 0.4261121367127314
Coefficient of PreviousMarks 1.0292843901315005
Final Marks of Student A 46.1684347306777
Final Marks of Student B 92.62396751134057
Final Marks of Student C 60.541869286530044